### ISSUE TITLE
Bullet threads not properly aligned

### ISSUE THREAD

**Issue by GuessWhatBBQ** [kirso/logseq-panic-theme#9]
This is probably happening because of some change in the logseq ui

Adding the following code snippet to my custom.css fixed the issue
```css
.ls-block[haschild] > div > .block-content-wrapper::before {
  left: -13px;
}

.ls-block .ls-block > div > div.items-center::before {
  right: 10px;
}
```
I've essentially updated the css imported from bullet_threading.scss by this theme
